version: '3'

services:
  api:
    build: ./docker/apache
    container_name: gstock_api
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
      - 8000:8000
    links:
      - db

  db:
    image: mysql:5.7
    container_name: gstock_db
    ports:
      - 3606:3606
    environment:
      MYSQL_DATABASE: gstock_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: gstock_api
      MYSQL_ROOT_PASSWORD: gstock_api

  phpmyadmin:
    image: phpmyadmin
    container_name: gstock_phpmyadmin
    ports:
      - 8080:80
    links:
      - db
