version: '3'

services:
  api:
    build: ./docker/apache
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    links:
      - db

  db:
    image: mysql
    ports:
      - 3606:3606
    environment:
      MYSQL_DATABASE: gstock_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: gstock_api
      MYSQL_ROOT_PASSWORD: gstock_api

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - db
